---

- hosts: DC1
  tasks:
    - name: Windows Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      become: true
      become_method: runas
      reboot: "{{ isreboot }}"
      reboot_timeout: "{{ timeout }}"