---

- hosts: DC1
  tasks:
    - name: 윈도우 업데이트 시작
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      become: true
      become_method: runas
      reboot: "{{ isreboot }}"
      reboot_timeout: "{{ timeout }}"