---

- hosts: DC1
  tasks:
    - name: add dns cname
      win_command: "powershell.exe -ExecutionPolicy Bypass -File C:\\Ansible\\ps1\\add_dns_cname.ps1 {{ record }} {{ host }} {{ cname }} {{ ttl }}"