---

- hosts: DC1
  tasks:
    - name: change password ad user
      win_user:
        name: "{{ name }}"
        password: "{{ password }}"
        state: present
      when: password == password_check